<?php

namespace App\Form;

use App\Classe\Pourcentage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PourcentageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pourcentage', PercentType::class, [
                'label' => false,
                'required' => false,
                'attr' => [
                    'placeholder' => "Augmenter le pourcentage...",
                    'class' => 'form-control-sm'
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => "Appliquer",
                'attr' => [
                    'class' => "btn btn-block btn-dark"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'csrf_protection' => false,
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }

}
