<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Range;

class PourcentageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pourcentage', PercentType::class, [
                'label' => false,
                'required' => false,
                'mapped' => false,
                'attr' => [
                    'placeholder' => "Augmenter ou diminuer le pourcentage...",
                    'class' => 'form-control-sm',
                    'autocomplete' => 'off'
                ],
                'constraints' => [
                    new Range([
                        'min' => -100,
                        'max' => 100,
                        'notInRangeMessage' => 'Pourcentage entre {{ min }}et {{ max }}'
                    ])
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => "Appliquer",
                'attr' => [
                    'class' => "btn  btn-dark"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'csrf_protection' => false,
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }

}
